"""Tests for drift.reporters.github_pr."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

import pytest
import responses

from drift.models import (
    ClaimKind,
    CodeFact,
    DocClaim,
    DriftItem,
    DriftReport,
    FactKind,
    Parameter,
    Severity,
)
from drift.reporters.github_pr import COMMENT_MARKER, GitHubPRReporter


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_drift_report() -> DriftReport:
    """A drift report with mixed severity items."""
    fact = CodeFact(
        name="process_data",
        kind=FactKind.FUNCTION,
        source_file=Path("src/processor.py"),
        line_number=42,
        parameters=[
            Parameter(name="input_data", type_annotation="dict"),
            Parameter(name="strict", type_annotation="bool", default="False"),
        ],
        return_type="dict",
    )

    claim = DocClaim(
        raw_text="process_data(input_data: dict) -> dict",
        kind=ClaimKind.FUNCTION_SIGNATURE,
        doc_file=Path("README.md"),
        line_number=10,
        name="process_data",
    )

    error_item = DriftItem(
        fact=fact,
        claim=claim,
        severity=Severity.ERROR,
        category="missing_param",
        message="Parameter 'strict' is documented but missing in code",
        suggestion="Add 'strict: bool = False' to the function signature",
        confidence=1.0,
    )

    warning_item = DriftItem(
        fact=None,
        claim=DocClaim(
            raw_text="configure()",
            kind=ClaimKind.FUNCTION_SIGNATURE,
            doc_file=Path("CHANGELOG.md"),
            line_number=5,
            name="configure",
        ),
        severity=Severity.WARNING,
        category="documented_but_missing",
        message="configure is documented but not found in code",
        confidence=0.9,
    )

    info_item = DriftItem(
        fact=CodeFact(
            name="helper",
            kind=FactKind.FUNCTION,
            source_file=Path("src/helper.py"),
            line_number=1,
            parameters=[],
        ),
        claim=None,
        severity=Severity.INFO,
        category="undocumented",
        message="helper is found in code but has no documentation",
        confidence=0.8,
    )

    return DriftReport(
        scanned_path=Path("."),
        facts=[fact],
        claims=[claim],
        drift_items=[error_item, warning_item, info_item],
        errors=[],
    )


# ---------------------------------------------------------------------------
# Tests: _build_comment_body
# ---------------------------------------------------------------------------


def test_build_comment_body_contains_marker(sample_drift_report):
    """Comment body starts with the marker so we can find it later."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert body.startswith(COMMENT_MARKER)


def test_build_comment_body_has_table(sample_drift_report):
    """Comment body contains a markdown table."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    lines = body.splitlines()
    # Find the header separator
    assert any(l.startswith("| Severity |") for l in lines)
    assert any(l.startswith("|----------|") for l in lines)


def test_build_comment_body_includes_error_row(sample_drift_report):
    """ERROR-severity items appear in the table with the right label."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "🔴 error" in body
    assert "missing_param" in body


def test_build_comment_body_includes_warning_row(sample_drift_report):
    """WARNING-severity items appear in the table with the right label."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "🟡 warning" in body
    assert "documented_but_missing" in body


def test_build_comment_body_includes_info_row(sample_drift_report):
    """INFO-severity items appear in the table."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "🔵 info" in body


def test_build_comment_body_has_footer(sample_drift_report):
    """Footer contains drift attribution and stats."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "Generated by [drift]" in body
    assert "1 🔴" in body  # 1 error
    assert "1 🟡" in body   # 1 warning
    assert "1 🔵" in body   # 1 info


def test_build_comment_body_fact_signature_rendered(sample_drift_report):
    """Code fact signature appears in the Fact column."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "process_data" in body


def test_build_comment_body_no_drift(empty_drift_report):
    """When there are no drift items the body still renders cleanly."""
    reporter = GitHubPRReporter(empty_drift_report)
    body = reporter._build_comment_body()
    assert COMMENT_MARKER in body
    assert "📋 Drift Report" in body


@pytest.fixture
def empty_drift_report() -> DriftReport:
    """A report with no drift items."""
    return DriftReport(scanned_path=Path("."))


# ---------------------------------------------------------------------------
# Tests: in_github_actions
# ---------------------------------------------------------------------------


def test_in_github_actions_true(monkeypatch):
    """Returns True when GITHUB_ACTIONS is set."""
    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    assert reporter.in_github_actions() is True


def test_in_github_actions_false():
    """Returns False when GITHUB_ACTIONS is not set."""
    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    assert reporter.in_github_actions() is False


# ---------------------------------------------------------------------------
# Tests: detect_pr_from_github_output
# ---------------------------------------------------------------------------


def test_detect_pr_from_github_output(tmp_path, monkeypatch):
    """Reads pr_number and repo from GITHUB_OUTPUT file."""
    github_output = tmp_path / "github_output.txt"
    github_output.write_text("pr_number=42\nrepo=my-org/my-repo\n")
    monkeypatch.setenv("GITHUB_OUTPUT", str(github_output))

    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    pr_number, repo = reporter.detect_pr_from_github_output()

    assert pr_number == 42
    assert repo == "my-org/my-repo"


def test_detect_pr_from_github_output_missing(monkeypatch):
    """Returns (None, None) when GITHUB_OUTPUT is not set."""
    monkeypatch.delenv("GITHUB_OUTPUT", raising=False)
    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    pr_number, repo = reporter.detect_pr_from_github_output()
    assert pr_number is None
    assert repo is None


# ---------------------------------------------------------------------------
# Tests: _find_existing_comment_id
# ---------------------------------------------------------------------------


@responses.activate
def test_find_existing_comment_id_found():
    """Returns comment ID when our marker comment exists."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[
            {"id": 100, "body": "some other comment"},
            {"id": 200, "body": f"{COMMENT_MARKER}\n## Drift Report"},
            {"id": 300, "body": "another comment"},
        ],
        status=200,
    )

    reporter = GitHubPRReporter(
        DriftReport(scanned_path=Path(".")),
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    comment_id = reporter._find_existing_comment_id()
    assert comment_id == 200


@responses.activate
def test_find_existing_comment_id_not_found():
    """Returns None when no matching comment exists."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[{"id": 100, "body": "some other comment"}],
        status=200,
    )

    reporter = GitHubPRReporter(
        DriftReport(scanned_path=Path(".")),
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    comment_id = reporter._find_existing_comment_id()
    assert comment_id is None


@responses.activate
def test_find_existing_comment_id_no_api_base():
    """Returns None when api_base is not set (no repo)."""
    reporter = GitHubPRReporter(
        DriftReport(scanned_path=Path(".")),
        token="fake-token",
        pr_number=42,
        repo=None,  # no repo
    )
    comment_id = reporter._find_existing_comment_id()
    assert comment_id is None


# ---------------------------------------------------------------------------
# Tests: report_github_pr — post new comment
# ---------------------------------------------------------------------------


@responses.activate
def test_report_github_pr_posts_new_comment(sample_drift_report):
    """Posts a new comment when no existing comment is found."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[],
        status=200,
    )
    responses.add(
        responses.POST,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json={"id": 999},
        status=201,
    )

    reporter = GitHubPRReporter(
        sample_drift_report,
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()

    assert success is True
    assert len(responses.calls) == 2
    assert responses.calls[1].request.method == "POST"


@responses.activate
def test_report_github_pr_updates_existing_comment(sample_drift_report):
    """Patches existing comment when found."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[{"id": 200, "body": f"{COMMENT_MARKER}\nold content"}],
        status=200,
    )
    responses.add(
        responses.PATCH,
        "https://api.github.com/repos/my-org/my-repo/issues/comments/200",
        json={"id": 200},
        status=200,
    )

    reporter = GitHubPRReporter(
        sample_drift_report,
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()

    assert success is True
    assert len(responses.calls) == 2
    assert responses.calls[1].request.method == "PATCH"
    assert "200" in responses.calls[1].request.url


def test_report_github_pr_no_token(sample_drift_report):
    """Gracefully skips when no token is available."""
    reporter = GitHubPRReporter(
        sample_drift_report,
        token=None,
        pr_number=42,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()
    assert success is False


def test_report_github_pr_no_pr_number(sample_drift_report):
    """Gracefully skips when no PR number is available."""
    reporter = GitHubPRReporter(
        sample_drift_report,
        token="fake-token",
        pr_number=None,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()
    assert success is False


# ---------------------------------------------------------------------------
# Tests: has_errors
# ---------------------------------------------------------------------------


def test_has_errors_true(sample_drift_report):
    """Returns True when the report has ERROR items."""
    reporter = GitHubPRReporter(sample_drift_report)
    assert reporter.has_errors() is True


def test_has_errors_false_when_only_warnings():
    """Returns False when there are only WARNING/INFO items."""
    report = DriftReport(
        scanned_path=Path("."),
        drift_items=[
            DriftItem(
                severity=Severity.WARNING,
                category="documented_but_missing",
                message="foo",
            )
        ],
    )
    reporter = GitHubPRReporter(report)
    assert reporter.has_errors() is False


def test_has_errors_false_when_empty():
    """Returns False on an empty report."""
    report = DriftReport(scanned_path=Path("."))
    reporter = GitHubPRReporter(report)
    assert reporter.has_errors() is False


# ---------------------------------------------------------------------------
# Tests: GITHUB_OUTPUT auto-detection (integration path)
# ---------------------------------------------------------------------------


@responses.activate
def test_report_github_pr_uses_github_output_detection(tmp_path, monkeypatch):
    """When repo/pr are not set but GITHUB_OUTPUT provides them, uses those."""
    github_output = tmp_path / "github_output.txt"
    github_output.write_text("pr_number=42\nrepo=my-org/my-repo\n")
    monkeypatch.setenv("GITHUB_OUTPUT", str(github_output))
    monkeypatch.setenv("GITHUB_TOKEN", "env-token")

    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[],
        status=200,
    )
    responses.add(
        responses.POST,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json={"id": 1},
        status=201,
    )

    report = DriftReport(scanned_path=Path("."))
    reporter = GitHubPRReporter(report)
    success = reporter.report_github_pr()

    assert success is True
    assert reporter.pr_number == 42
    assert reporter.repo == "my-org/my-repo"
