"""Tests for drift.reporters.github_pr."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

import pytest
import responses

from drift.models import (
    ClaimKind,
    CodeFact,
    DocClaim,
    DriftItem,
    DriftReport,
    FactKind,
    Parameter,
    Severity,
)
from drift.reporters.github_pr import COMMENT_MARKER, GitHubPRReporter


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_drift_report() -> DriftReport:
    """A drift report with mixed severity items."""
    fact = CodeFact(
        name="process_data",
        kind=FactKind.FUNCTION,
        source_file=Path("src/processor.py"),
        line_number=42,
        parameters=[
            Parameter(name="input_data", type_annotation="dict"),
            Parameter(name="strict", type_annotation="bool", default="False"),
        ],
        return_type="dict",
    )

    claim = DocClaim(
        raw_text="process_data(input_data: dict) -> dict",
        kind=ClaimKind.FUNCTION_SIGNATURE,
        doc_file=Path("README.md"),
        line_number=10,
        name="process_data",
    )

    error_item = DriftItem(
        fact=fact,
        claim=claim,
        severity=Severity.ERROR,
        category="missing_param",
        message="Parameter 'strict' is documented but missing in code",
        suggestion="Add 'strict: bool = False' to the function signature",
        confidence=1.0,
    )

    warning_item = DriftItem(
        fact=None,
        claim=DocClaim(
            raw_text="configure()",
            kind=ClaimKind.FUNCTION_SIGNATURE,
            doc_file=Path("CHANGELOG.md"),
            line_number=5,
            name="configure",
        ),
        severity=Severity.WARNING,
        category="documented_but_missing",
        message="configure is documented but not found in code",
        confidence=0.9,
    )

    info_item = DriftItem(
        fact=CodeFact(
            name="helper",
            kind=FactKind.FUNCTION,
            source_file=Path("src/helper.py"),
            line_number=1,
            parameters=[],
        ),
        claim=None,
        severity=Severity.INFO,
        category="undocumented",
        message="helper is found in code but has no documentation",
        confidence=0.8,
    )

    return DriftReport(
        scanned_path=Path("."),
        facts=[fact],
        claims=[claim],
        drift_items=[error_item, warning_item, info_item],
        errors=[],
    )


# ---------------------------------------------------------------------------
# Tests: _build_comment_body
# ---------------------------------------------------------------------------


def test_build_comment_body_contains_marker(sample_drift_report):
    """Comment body starts with the marker so we can find it later."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert body.startswith(COMMENT_MARKER)


def test_build_comment_body_has_table(sample_drift_report):
    """Comment body contains a markdown table."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    lines = body.splitlines()
    # Find the header separator
    assert any(l.startswith("| Severity |") for l in lines)
    assert any(l.startswith("|----------|") for l in lines)


def test_build_comment_body_includes_error_row(sample_drift_report):
    """ERROR-severity items appear in the table with the right label."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "🔴 error" in body
    assert "missing_param" in body


def test_build_comment_body_includes_warning_row(sample_drift_report):
    """WARNING-severity items appear in the table with the right label."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "🟡 warning" in body
    assert "documented_but_missing" in body


def test_build_comment_body_includes_info_row(sample_drift_report):
    """INFO-severity items appear in the table."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "🔵 info" in body


def test_build_comment_body_has_footer(sample_drift_report):
    """Footer contains drift attribution and stats."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "Generated by [drift]" in body
    assert "1 🔴" in body  # 1 error
    assert "1 🟡" in body   # 1 warning
    assert "1 🔵" in body   # 1 info


def test_build_comment_body_fact_signature_rendered(sample_drift_report):
    """Code fact signature appears in the Fact column."""
    reporter = GitHubPRReporter(sample_drift_report)
    body = reporter._build_comment_body()
    assert "process_data" in body


def test_build_comment_body_no_drift(empty_drift_report):
    """When there are no drift items the body still renders cleanly."""
    reporter = GitHubPRReporter(empty_drift_report)
    body = reporter._build_comment_body()
    assert COMMENT_MARKER in body
    assert "📋 Drift Report" in body


@pytest.fixture
def empty_drift_report() -> DriftReport:
    """A report with no drift items."""
    return DriftReport(scanned_path=Path("."))


# ---------------------------------------------------------------------------
# Tests: in_github_actions
# ---------------------------------------------------------------------------


def test_in_github_actions_true(monkeypatch):
    """Returns True when GITHUB_ACTIONS is set."""
    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    assert reporter.in_github_actions() is True


def test_in_github_actions_false():
    """Returns False when GITHUB_ACTIONS is not set."""
    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    assert reporter.in_github_actions() is False


# ---------------------------------------------------------------------------
# Tests: detect_pr_from_github_output
# ---------------------------------------------------------------------------


def test_detect_pr_from_github_output(tmp_path, monkeypatch):
    """Reads pr_number and repo from GITHUB_OUTPUT file."""
    github_output = tmp_path / "github_output.txt"
    github_output.write_text("pr_number=42\nrepo=my-org/my-repo\n")
    monkeypatch.setenv("GITHUB_OUTPUT", str(github_output))

    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    pr_number, repo = reporter.detect_pr_from_github_output()

    assert pr_number == 42
    assert repo == "my-org/my-repo"


def test_detect_pr_from_github_output_missing(monkeypatch):
    """Returns (None, None) when GITHUB_OUTPUT is not set."""
    monkeypatch.delenv("GITHUB_OUTPUT", raising=False)
    reporter = GitHubPRReporter(DriftReport(scanned_path=Path(".")))
    pr_number, repo = reporter.detect_pr_from_github_output()
    assert pr_number is None
    assert repo is None


# ---------------------------------------------------------------------------
# Tests: _find_existing_comment_id
# ---------------------------------------------------------------------------


@responses.activate
def test_find_existing_comment_id_found():
    """Returns comment ID when our marker comment exists."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[
            {"id": 100, "body": "some other comment"},
            {"id": 200, "body": f"{COMMENT_MARKER}\n## Drift Report"},
            {"id": 300, "body": "another comment"},
        ],
        status=200,
    )

    reporter = GitHubPRReporter(
        DriftReport(scanned_path=Path(".")),
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    comment_id = reporter._find_existing_comment_id()
    assert comment_id == 200


@responses.activate
def test_find_existing_comment_id_not_found():
    """Returns None when no matching comment exists."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[{"id": 100, "body": "some other comment"}],
        status=200,
    )

    reporter = GitHubPRReporter(
        DriftReport(scanned_path=Path(".")),
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    comment_id = reporter._find_existing_comment_id()
    assert comment_id is None


@responses.activate
def test_find_existing_comment_id_no_api_base():
    """Returns None when api_base is not set (no repo)."""
    reporter = GitHubPRReporter(
        DriftReport(scanned_path=Path(".")),
        token="fake-token",
        pr_number=42,
        repo=None,  # no repo
    )
    comment_id = reporter._find_existing_comment_id()
    assert comment_id is None


# ---------------------------------------------------------------------------
# Tests: report_github_pr — post new comment
# ---------------------------------------------------------------------------


@responses.activate
def test_report_github_pr_posts_new_comment(sample_drift_report):
    """Posts a new comment when no existing comment is found."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[],
        status=200,
    )
    responses.add(
        responses.POST,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json={"id": 999},
        status=201,
    )

    reporter = GitHubPRReporter(
        sample_drift_report,
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()

    assert success is True
    assert len(responses.calls) == 2
    assert responses.calls[1].request.method == "POST"


@responses.activate
def test_report_github_pr_updates_existing_comment(sample_drift_report):
    """Patches existing comment when found."""
    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[{"id": 200, "body": f"{COMMENT_MARKER}\nold content"}],
        status=200,
    )
    responses.add(
        responses.PATCH,
        "https://api.github.com/repos/my-org/my-repo/issues/comments/200",
        json={"id": 200},
        status=200,
    )

    reporter = GitHubPRReporter(
        sample_drift_report,
        token="fake-token",
        pr_number=42,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()

    assert success is True
    assert len(responses.calls) == 2
    assert responses.calls[1].request.method == "PATCH"
    assert "200" in responses.calls[1].request.url


def test_report_github_pr_no_token(sample_drift_report):
    """Gracefully skips when no token is available."""
    reporter = GitHubPRReporter(
        sample_drift_report,
        token=None,
        pr_number=42,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()
    assert success is False


def test_report_github_pr_no_pr_number(sample_drift_report):
    """Gracefully skips when no PR number is available."""
    reporter = GitHubPRReporter(
        sample_drift_report,
        token="fake-token",
        pr_number=None,
        repo="my-org/my-repo",
    )
    success = reporter.report_github_pr()
    assert success is False


# ---------------------------------------------------------------------------
# Tests: has_errors
# ---------------------------------------------------------------------------


def test_has_errors_true(sample_drift_report):
    """Returns True when the report has ERROR items."""
    reporter = GitHubPRReporter(sample_drift_report)
    assert reporter.has_errors() is True


def test_has_errors_false_when_only_warnings():
    """Returns False when there are only WARNING/INFO items."""
    report = DriftReport(
        scanned_path=Path("."),
        drift_items=[
            DriftItem(
                severity=Severity.WARNING,
                category="documented_but_missing",
                message="foo",
            )
        ],
    )
    reporter = GitHubPRReporter(report)
    assert reporter.has_errors() is False


def test_has_errors_false_when_empty():
    """Returns False on an empty report."""
    report = DriftReport(scanned_path=Path("."))
    reporter = GitHubPRReporter(report)
    assert reporter.has_errors() is False


# ---------------------------------------------------------------------------
# Tests: GITHUB_OUTPUT auto-detection (integration path)
# ---------------------------------------------------------------------------


@responses.activate
def test_report_github_pr_uses_github_output_detection(tmp_path, monkeypatch):
    """When repo/pr are not set but GITHUB_OUTPUT provides them, uses those."""
    github_output = tmp_path / "github_output.txt"
    github_output.write_text("pr_number=42\nrepo=my-org/my-repo\n")
    monkeypatch.setenv("GITHUB_OUTPUT", str(github_output))
    monkeypatch.setenv("GITHUB_TOKEN", "env-token")

    responses.add(
        responses.GET,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json=[],
        status=200,
    )
    responses.add(
        responses.POST,
        "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
        json={"id": 1},
        status=201,
    )

    report = DriftReport(scanned_path=Path("."))
    reporter = GitHubPRReporter(report)
    success = reporter.report_github_pr()

    assert success is True
    assert reporter.pr_number == 42
    assert reporter.repo == "my-org/my-repo"


# ---------------------------------------------------------------------------
# E2E Tests: full scan -> report flow with mock GitHub API
# ---------------------------------------------------------------------------


class TestGitHubPRE2E:
    """End-to-end integration tests exercising scan -> GitHub PR report flow.

    These tests create real source files, run DriftScanner to produce a report,
    then verify that GitHubPRReporter correctly posts/updates a PR comment with
    content derived from the actual scan results.
    """

    @responses.activate
    def test_e2e_scan_report_posts_new_comment_with_drift(self, tmp_path):
        """Full scan->report flow: drift found, posts new PR comment."""
        # Create a Python source file with a function
        src_file = tmp_path / "processor.py"
        src_file.write_text(
            "def process_data(input_data: dict, strict: bool = False) -> dict:\n"
            "    '''Process input data.'''\n"
            "    return input_data\n"
        )

        # Create a markdown file that documents the function but MISSING the `strict` param
        md_file = tmp_path / "README.md"
        md_file.write_text(
            "# API\n\n"
            "## process_data\n\n"
            "```python\n"
            "def process_data(input_data: dict) -> dict\n"
            "```\n"
        )

        # Run actual drift scan
        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # Verify drift was detected
        assert len(report.drift_items) >= 1
        error_items = [d for d in report.drift_items if d.severity == Severity.ERROR]
        assert len(error_items) >= 1

        # Set up mock GitHub API - no existing comment
        responses.add(
            responses.GET,
            "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
            json=[],
            status=200,
        )
        responses.add(
            responses.POST,
            "https://api.github.com/repos/my-org/my-repo/issues/42/comments",
            json={"id": 999},
            status=201,
        )

        # Report to GitHub PR
        reporter = GitHubPRReporter(
            report,
            token="fake-token",
            pr_number=42,
            repo="my-org/my-repo",
        )
        success = reporter.report_github_pr()

        assert success is True
        assert len(responses.calls) == 2
        assert responses.calls[1].request.method == "POST"

        # Verify the posted comment body contains scan-derived content
        import json

        posted_body = json.loads(responses.calls[1].request.body)["body"]
        assert COMMENT_MARKER in posted_body
        assert "process_data" in posted_body
        assert "🔴" in posted_body or "error" in posted_body.lower()

    @responses.activate
    def test_e2e_scan_report_updates_existing_comment(self, tmp_path):
        """Full scan->report flow: existing drift comment is updated (upsert)."""
        # Create a Python file with a function missing a parameter
        src_file = tmp_path / "api.py"
        src_file.write_text(
            "def fetch_user(user_id: int, include_roles: bool = True) -> dict:\n"
            "    '''Fetch a user record.'''\n"
            "    return {}\n"
        )

        # Create markdown that documents fetch_user WITHOUT include_roles
        md_file = tmp_path / "README.md"
        md_file.write_text(
            "# API\n\n"
            "```python\n"
            "def fetch_user(user_id: int) -> dict\n"
            "```\n"
        )

        # Run actual drift scan
        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # Set up mock GitHub API - existing drift comment found
        responses.add(
            responses.GET,
            "https://api.github.com/repos/my-org/my-repo/issues/99/comments",
            json=[
                {"id": 200, "body": f"{COMMENT_MARKER}\n## Drift Report\nold content"}
            ],
            status=200,
        )
        responses.add(
            responses.PATCH,
            "https://api.github.com/repos/my-org/my-repo/issues/comments/200",
            json={"id": 200},
            status=200,
        )

        # Report to GitHub PR
        reporter = GitHubPRReporter(
            report,
            token="fake-token",
            pr_number=99,
            repo="my-org/my-repo",
        )
        success = reporter.report_github_pr()

        assert success is True
        assert len(responses.calls) == 2
        assert responses.calls[1].request.method == "PATCH"

        # Verify PATCH URL contains the existing comment ID
        assert "200" in responses.calls[1].request.url

    def test_e2e_handles_missing_github_token(self, tmp_path):
        """Gracefully skips when GITHUB_TOKEN is not set."""
        src_file = tmp_path / "foo.py"
        src_file.write_text("def bar(x: int) -> str:\n    return str(x)\n")
        md_file = tmp_path / "README.md"
        md_file.write_text("```python\ndef bar(x: int) -> str\n```\n")

        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # No token provided
        reporter = GitHubPRReporter(
            report,
            token=None,
            pr_number=42,
            repo="my-org/my-repo",
        )
        success = reporter.report_github_pr()

        assert success is False

    def test_e2e_handles_missing_pr_number(self, tmp_path):
        """Gracefully skips when PR number is not available."""
        src_file = tmp_path / "foo.py"
        src_file.write_text("def bar(x: int) -> str:\n    return str(x)\n")
        md_file = tmp_path / "README.md"
        md_file.write_text("```python\ndef bar(x: int) -> str\n```\n")

        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # PR number not set
        reporter = GitHubPRReporter(
            report,
            token="fake-token",
            pr_number=None,
            repo="my-org/my-repo",
        )
        success = reporter.report_github_pr()

        assert success is False

    def test_e2e_handles_missing_repo(self, tmp_path):
        """Gracefully skips when repo is not available."""
        src_file = tmp_path / "foo.py"
        src_file.write_text("def bar(x: int) -> str:\n    return str(x)\n")
        md_file = tmp_path / "README.md"
        md_file.write_text("```python\ndef bar(x: int) -> str\n```\n")

        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # Repo not set
        reporter = GitHubPRReporter(
            report,
            token="fake-token",
            pr_number=42,
            repo=None,
        )
        success = reporter.report_github_pr()

        assert success is False

    @responses.activate
    def test_e2e_no_drift_posts_healthy_comment(self, tmp_path):
        """When no drift is found, posts a comment indicating clean state."""
        # Create a Python file and correctly documented markdown
        src_file = tmp_path / "utils.py"
        src_file.write_text(
            "def greet(name: str) -> str:\n"
            "    '''Return a greeting.'''\n"
            "    return f'Hello, {name}'\n"
        )

        md_file = tmp_path / "README.md"
        md_file.write_text(
            "# Utils\n\n"
            "## greet\n\n"
            "```python\n"
            "def greet(name: str) -> str\n"
            "```\n"
        )

        # Run actual drift scan
        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # Verify no drift
        assert len(report.drift_items) == 0

        # Set up mock GitHub API
        responses.add(
            responses.GET,
            "https://api.github.com/repos/my-org/my-repo/issues/1/comments",
            json=[],
            status=200,
        )
        responses.add(
            responses.POST,
            "https://api.github.com/repos/my-org/my-repo/issues/1/comments",
            json={"id": 1},
            status=201,
        )

        # Report to GitHub PR
        reporter = GitHubPRReporter(
            report,
            token="fake-token",
            pr_number=1,
            repo="my-org/my-repo",
        )
        success = reporter.report_github_pr()

        assert success is True

        # Verify posted comment body
        import json

        posted_body = json.loads(responses.calls[1].request.body)["body"]
        assert COMMENT_MARKER in posted_body
        assert "📋 Drift Report" in posted_body
        # Should show 0 errors/warnings/info
        assert "0 🔴" in posted_body or "0 error" in posted_body.lower()

    @responses.activate
    def test_e2e_multiple_drift_items_rendered_correctly(self, tmp_path):
        """Comment body correctly renders multiple drift items of different severities."""
        # Create Python file with multiple functions having issues
        src_file = tmp_path / "api.py"
        src_file.write_text(
            "def get_user(user_id: int, include_profile: bool = True) -> dict:\n"
            "    '''Get user.'''\n"
            "    return {}\n\n"
            "def update_user(user_id: int, data: dict) -> None:\n"
            "    '''Update user.'''\n"
            "    pass\n\n"
            "def delete_user(user_id: int) -> bool:\n"
            "    '''Delete user.'''\n"
            "    return True\n"
        )

        # Markdown with mismatched signatures:
        # - get_user: documented but missing include_profile (ERROR)
        # - update_user: documented but missing data (ERROR)
        # - delete_user: correctly documented (no drift for this one)
        md_file = tmp_path / "README.md"
        md_file.write_text(
            "# API\n\n"
            "```python\n"
            "def get_user(user_id: int) -> dict\n"
            "def update_user(user_id: int) -> None\n"
            "def delete_user(user_id: int) -> bool\n"
            "```\n"
        )

        # Run actual drift scan
        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # Set up mock GitHub API
        responses.add(
            responses.GET,
            "https://api.github.com/repos/my-org/my-repo/issues/7/comments",
            json=[],
            status=200,
        )
        responses.add(
            responses.POST,
            "https://api.github.com/repos/my-org/my-repo/issues/7/comments",
            json={"id": 7},
            status=201,
        )

        # Report to GitHub PR
        reporter = GitHubPRReporter(
            report,
            token="fake-token",
            pr_number=7,
            repo="my-org/my-repo",
        )
        success = reporter.report_github_pr()

        assert success is True

        import json

        posted_body = json.loads(responses.calls[1].request.body)["body"]
        assert COMMENT_MARKER in posted_body
        assert "get_user" in posted_body
        assert "update_user" in posted_body
        # Should have multiple error entries
        assert posted_body.count("🔴") >= 2

    @responses.activate
    def test_e2e_api_failure_on_post_returns_false(self, tmp_path):
        """When GitHub API fails, report_github_pr returns False gracefully."""
        src_file = tmp_path / "foo.py"
        src_file.write_text(
            "def bar(x: int) -> str:\n"
            "    '''A function.'''\n"
            "    return str(x)\n"
        )
        md_file = tmp_path / "README.md"
        md_file.write_text(
            "# Docs\n"
            "```python\n"
            "def bar(x: int, extra: str) -> str\n"
            "```\n"
        )

        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # Mock API to return server error
        responses.add(
            responses.GET,
            "https://api.github.com/repos/my-org/my-repo/issues/5/comments",
            json=[],
            status=200,
        )
        responses.add(
            responses.POST,
            "https://api.github.com/repos/my-org/my-repo/issues/5/comments",
            json={"message": "Server Error"},
            status=500,
        )

        reporter = GitHubPRReporter(
            report,
            token="fake-token",
            pr_number=5,
            repo="my-org/my-repo",
        )
        success = reporter.report_github_pr()

        assert success is False

    @responses.activate
    def test_e2e_github_output_detection_with_real_scan(self, tmp_path, monkeypatch):
        """GITHUB_OUTPUT detection works with actual scan results."""
        # Create a Python file with an undocumented function
        src_file = tmp_path / "helper.py"
        src_file.write_text(
            "def helper(a: int, b: str = 'hi') -> bool:\n"
            "    '''A helper.'''\n"
            "    return True\n"
        )

        # Markdown correctly documents it (no drift)
        md_file = tmp_path / "README.md"
        md_file.write_text(
            "# Helper\n\n"
            "```python\n"
            "def helper(a: int, b: str = 'hi') -> bool\n"
            "```\n"
        )

        # Set up GITHUB_OUTPUT file
        github_output = tmp_path / "github_output.txt"
        github_output.write_text("pr_number=10\nrepo=my-org/my-repo\n")
        monkeypatch.setenv("GITHUB_OUTPUT", str(github_output))
        monkeypatch.setenv("GITHUB_TOKEN", "env-token")

        # Run actual drift scan
        from drift.scanner import DriftScanner

        scanner = DriftScanner(tmp_path)
        report = scanner.scan()

        # Mock API
        responses.add(
            responses.GET,
            "https://api.github.com/repos/my-org/my-repo/issues/10/comments",
            json=[],
            status=200,
        )
        responses.add(
            responses.POST,
            "https://api.github.com/repos/my-org/my-repo/issues/10/comments",
            json={"id": 10},
            status=201,
        )

        # Report using auto-detection
        reporter = GitHubPRReporter(report)
        success = reporter.report_github_pr()

        assert success is True
        assert reporter.pr_number == 10
        assert reporter.repo == "my-org/my-repo"
